# This is configuration for 75% keyboard - I use Ajaz AK820.
# Original file source: onto /etc/ked/default.conf
#
# Remove all the xmodmap configuration in .xession file
# (sleep 1 && xmodmap ~/.local/bin/emacs_keyboard) &
#
# Install keyd - enable keyd with systemcl and copy this file into
# original file  source

[ids]
*

[main]

# Exchange keys
capslock = leftcontrol
leftcontrol = esc
esc = capslock

# Disable Right Ctrl
rightcontrol = noop

# Left Alt activates navigation layer
rightalt = layer(nav)

# Physical arrows disabled normally
left = noop
right = noop
up = noop
down = noop

[nav]

#Arrows work only while RightAlt is held
left = left
right = right
up = up
down = down